name: Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python & Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      - name: Set up TruffleHog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: Create output directories
        run: mkdir -p output/reports output/json output/csv

      - name: Run Semgrep for secrets
        run: |
          echo "Running Semgrep..."
          semgrep scan --config auto . --json > output/json/semgrep_report.json

      - name: Run TruffleHog for secrets
        run: |
          echo "Running TruffleHog..."
          trufflehog filesystem . --include-detectors=all --no-verification --json > output/json/trufflehog_report.json

      - name: Combine and extract to CSV
        run: |
          chmod +x ./extract_secrets_to_csv2.py
          python3 extract_secrets_to_csv2.py output/json/trufflehog_report.json output/json/semgrep_report.json output/csv/secrets_combined_report.csv

      - name: Show extracted secrets in GitHub Actions logs
        run: |
          echo "================== Extracted Secrets (CSV Preview) =================="
          cat output/csv/secrets_combined_report.csv || echo "No secrets found"
          echo "===================================================================="

      - name: Upload CSV report(s)
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-csv
          path: output/csv/

      - name: Upload JSON reports
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-json
          path: output/json/
